package com.SpringBoot.Practice.Test;

import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

@Component
@Scope("prototype")
public class Report {

    public String generateReport() {
        return "This is a sample report generated by the Report class.";
    }
}
