


server.port = 0000
app.email.provider = defaultProvider
app.email.message = This is a default email message. Please set the provider and message in the application-dev.properties or application-prod.properties file.